train:
  _target_: src.datasets.LibriSpeechDataset
  data_dir: ${oc.env:LIBRISPEECH_DIR,data/librispeech}
  part: "train-clean-100"
  sample_rate: ${sample_rate}
  crop_length: 8000
test:
  _target_: src.datasets.LibriSpeechDataset
  data_dir: ${oc.env:LIBRISPEECH_DIR,data/librispeech}
  part: "test-clean"
  sample_rate: ${sample_rate}
  crop_length: 8000
  limit: 200
