defaults:
  - model: soundstream
  - metrics: soundstream_eval
  - datasets: librispeech_eval
  - dataloader: soundstream_eval
  - transforms: soundstream
  - writer: cometml
  - _self_
sample_rate: 16000
inferencer:
  device_tensors: ["audio"]
  device: auto
  save_path: "test-clean"
  seed: 1
  save_audio: True
  from_pretrained: "saved/model_best.pth"
writer:
  run_name: "soundstream_eval"
