_target_: src.logger.CometMLWriter
project_name: "soundstream"
workspace: null
run_name: "soundstream_baseline"
mode: "online"
loss_names:
  - "loss"
  - "loss_g"
  - "loss_d"
  - "loss_adv"
  - "loss_fm"
  - "loss_rec"
  - "loss_commit"
log_checkpoints: False
id_length: 32
